#ifndef ITER_COMMON_H
#define ITER_COMMON_H

#include "aeolus/utils.h"
#include "aeolus/generics.h"

#define Iterator(ITERABLE)          GenericName(ITERABLE, Iterator)
#define IterItem(ITERABLE)          CAT(Iterator(ITERABLE), Item)

/* ********* iter_curr *********** */
#define ITER_CURR_FUNC_NAME(ITERABLE)      CAT(Iterator(ITERABLE), _curr)
#define ITER_CURR_FUNC_SIGNATURE(ITERABLE) IterItem(ITERABLE)* ITER_CURR_FUNC_NAME(ITERABLE)(ITERABLE* const self)
#define ITER_CURR_FUNC_IMPL(ITERABLE)\
    ITER_CURR_FUNC_SIGNATURE(ITERABLE)

/* ********* iter_begin *********** */
#define ITER_BEGIN_FUNC_NAME(ITERABLE)       CAT(Iterator(ITERABLE), _begin)
#define ITER_BEGIN_FUNC_SIGNATURE(ITERABLE)  IterItem(ITERABLE)* ITER_BEGIN_FUNC_NAME(ITERABLE)(ITERABLE* const self)
#define ITER_BEGIN_FUNC_IMPL(ITERABLE)\
    ITER_BEGIN_FUNC_SIGNATURE(ITERABLE)

/* ********* iter_end *********** */
#define ITER_END_FUNC_NAME(ITERABLE)       CAT(Iterator(ITERABLE), _end)
#define ITER_END_FUNC_SIGNATURE(ITERABLE)  IterItem(ITERABLE)* ITER_END_FUNC_NAME(ITERABLE)(ITERABLE* const self)
#define ITER_END_FUNC_IMPL(ITERABLE)\
    ITER_END_FUNC_SIGNATURE(ITERABLE)

/* ********* iter_prev *********** */
#define ITER_PREV_FUNC_NAME(ITERABLE)       CAT(Iterator(ITERABLE), _prev)
#define ITER_PREV_FUNC_SIGNATURE(ITERABLE)  IterItem(ITERABLE)* ITER_PREV_FUNC_NAME(ITERABLE)(ITERABLE* const self)
#define ITER_PREV_FUNC_IMPL(ITERABLE)\
    ITER_PREV_FUNC_SIGNATURE(ITERABLE)

/* ********* iter_next *********** */
#define ITER_NEXT_FUNC_NAME(ITERABLE)       CAT(Iterator(ITERABLE), _next)
#define ITER_NEXT_FUNC_SIGNATURE(ITERABLE)  IterItem(ITERABLE)* ITER_NEXT_FUNC_NAME(ITERABLE)(ITERABLE* const self)
#define ITER_NEXT_FUNC_IMPL(ITERABLE)\
    ITER_NEXT_FUNC_SIGNATURE(ITERABLE)

#define ITER_IMPL(ITERABLE, CURR_IMPL, BEGIN_IMPL, END_IMPL, PREV_IMPL, NEXT_IMPL)\
    ITER_CURR_FUNC_IMPL(ITERABLE)  CURR_IMPL\
    ITER_BEGIN_FUNC_IMPL(ITERABLE) BEGIN_IMPL\
    ITER_END_FUNC_IMPL(ITERABLE)   END_IMPL\
    ITER_PREV_FUNC_IMPL(ITERABLE)  PREV_IMPL\
    ITER_NEXT_FUNC_IMPL(ITERABLE)  NEXT_IMPL\

#endif
